max_steps = 200

[model]
name = "JayZenith/GLYPH_SFT"
seq_len = 5120
attn = "sdpa"
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"

[buffer]
batch_size = 12
seq_len = 5120

[optim]
type = "adamw"
lr = 1e-6
weight_decay = 0.01

[loss]
type = "default"
teacher_tau = 0.0

[ckpt]
interval = 1000
