max_steps = 200

[model]
name = "Qwen/Qwen3-4B-Base"
seq_len = 4096
attn = "sdpa"
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"

[buffer]
batch_size = 64
seq_len = 4096

[optim]
type = "adamw"
lr = 1e-6
weight_decay = 0.01

[loss]
type = "default"
teacher_tau = 0.0

[ckpt]
interval = 1000
