use_sft_loss = false
filters = [
    { type = "gibberish", enforce = false, token_id_threshold = 100000, logprob_offset = 2.0 },
    { type = "repetition", enforce = false, window = 3000, prob_threshold = 0.99 },
    { type = "zero_advantage", enforce = false },
]
collect_inference_metrics = true
output_dir = "/workspace/glyph/rl_ablations/baseline/run_default"
batch_size = 48
max_inflight_rollouts = 48
rollouts_per_example = 4
seq_len = 2048
num_train_workers = 1
max_steps = 200
max_off_policy_steps = 8
max_async_level = 1
strict_async_level = false
bench = false
seed = 42
use_token_client = false
use_renderer = true
env_install_prerelease = false

[train]
num_workers = "auto"
max_retries = 0

[[train.env]]
id = "task-trace"
num_workers = 1
max_retries = 0
max_total_completion_tokens = -1

[train.env.args]
data_path = "/workspace/glyph/runs/rl1/rust_tool_prompts_8.jsonl"
max_samples = 512
max_trace_chars = 50000
timeout = 30

[train.env.extra_env_kwargs]
max_total_completion_tokens = -1
max_seq_len = 2048

[train.env.sampling]
temperature = 0.8
repetition_penalty = 1.0
max_completion_tokens = 512
min_tokens = 0

[train.env.sampling.extra_body]
top_k = -1
min_p = 0.0
return_token_ids = true

[train.sampling]
temperature = 0.8
repetition_penalty = 1.0
max_completion_tokens = 512
min_tokens = 0

[train.sampling.extra_body]

[client]
timeout = 1200
connect_timeout = 30.0
wait_for_ready_timeout = 1800
base_url = [
    "http://localhost:8000/v1",
]
api_key_var = "VLLM_API_KEY"
skip_model_check = false
dp_rank_count = 1

[client.headers]

[client.extra_headers_from_state]
X-Session-ID = "example_id"

[model]
name = "JayZenith/glyph-sft-v1"
trust_remote_code = false

[model.lora]
name = "JayZenith__glyph-sft-v1-adapter-r64-a64"
rank = 64
alpha = 64.0

[tokenizer]
name = "JayZenith/glyph-sft-v1"
trust_remote_code = false

[renderer]
name = "auto"
preserve_all_thinking = false
preserve_thinking_between_tool_calls = false

[optim]
lr = 0.0001

[buffer]
easy_fraction = 0.0
hard_fraction = 0.0
online_difficulty_filtering = false
hash_keys = [
    "env_name",
    "prompt",
]

[advantage]
type = "default"

[log]
level = "info"
vf_level = "info"
json_logging = false
log_data = false

[wandb]
project = "prime-rl"
offline = true

[wandb.log_extras]
samples = true
distributions = true
interval = 10

[ckpt]
interval = 1000
skip_progress = false
skip_buffer = false

[weight_broadcast]
type = "filesystem"

[rollout_transport]
type = "filesystem"

[experimental]
