enable_lora = true
max_loras = 8
max_cpu_loras = 100
max_lora_rank = 64
gpu_memory_utilization = 0.7
api_server_count = 1
data_parallel_rpc_port = 13345
seed = 0
enable_expert_parallel = false
all2all_backend = "allgather_reducescatter"
enable_eplb = false
enable_dbo = false
use_deep_gemm = false
enable_return_routed_experts = false
enable_fp32_lm_head = false

[server]
port = 8000
liveness_timeout_seconds = 30.0

[model]
name = "JayZenith/glyph-sft-v1"
trust_remote_code = false
dtype = "float16"
max_model_len = 4096
enforce_eager = true
tool_call_parser = "auto"

[parallel]
tp = 1
dp = 1

[weight_broadcast]
type = "filesystem"

[vllm_extra]
served_model_name = [
    "JayZenith/glyph-sft-v1",
    "Qwen/Qwen3-4B-Base",
    "JayZenith__glyph-sft-v1-adapter-r64-a64",
    "r64-a64.0",
]

[experimental]
